[connections.snowflake]
account = "DGIVXIM-RNB69144"
user = "CRBACK09"
password = "Cl@udio02041982"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true 
